# The URL the site will be built for
base_url = "https://www.mainframe.io"
default_language = "de"

title = "Mainframe"
description = "Website des Hackspace Mainframe"
author = "Markus Framer"

# Compilation settings
compile_sass = true
minify_html = false
build_search_index = false
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]

taxonomies = [
    { name = "Serie", feed = true, paginate_by = 10 },
    { name = "Typ", feed = true, paginate_by = 10 }
]

[link_checker]
skip_prefixes = []
skip_anchor_prefixes = []
internal_level = "error"
external_level = "error"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
paths_keep_dates = false

[markdown]
highlight_code = true
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true
lazy_async_image = true

[translations]
language = "Sprache"
not_found_content = "Dies sind nicht die Inhalte die du suchst!"
not_found = "Inhalt nicht gefunden"
locale_name = "de_DE"
publish_time = "veröffentlicht am %date% um %time% Uhr%author%"
all = "Alle"
images = "Bilder"
arrival = "Anreise"

closed = "Geschlossen"
closing = "Schließt bald"
open = "Geöffnet"
member = "Geschlossen (Member Only)"
keyholder = "Geschlossen (Keyholder Only)"

ifs_newest = "Neuste Images From Space"
ifs_more = "Viele weitere Fotos findest du hier:"

blog = "Blog"

[extra]
ifs_base_path = "https://www.mainframe.io/media/ifs-images"
bs_color_map = [
    "primary",
    "secondary",
    "success",
    "danger",
    "warning",
    "info",
    "light"
]

rooms = [
    { name = "spaceOpen", title = { de = "Mainframe", en = "Mainframe" } },
]

google_cal_id = "markusframer@gmail.com"
google_api_key = "AIzaSyB9pTX1ewZeRPc-rmq-Xp32wuuTW1P4U1U"

ktt_board_mail = "vorstand@kreativitaet-trifft-technik.de"
ktt_url = "https://www.kreativitaet-trifft-technik.de"

status_domain = "https://status.mainframe.io/"
